# Generated by Django 3.2.13 on 2022-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
