# Generated by Django 3.2.13 on 2022-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20220525_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsi',
            old_name='value',
            new_name='tf_1d',
        ),
        migrations.RemoveField(
            model_name='rsi',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='rsi',
            name='tf_1h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsi',
            name='tf_4h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
