# Generated by Django 3.2.13 on 2022-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20220525_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOVINGAVG168',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('tf_1h', models.FloatField()),
                ('tf_4h', models.FloatField()),
                ('tf_1d', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MOVINGAVG28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('tf_1h', models.FloatField()),
                ('tf_4h', models.FloatField()),
                ('tf_1d', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MOVINGAVG84',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('tf_1h', models.FloatField()),
                ('tf_4h', models.FloatField()),
                ('tf_1d', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='MOVINGAVG',
        ),
    ]
